### PR TITLE
Fixed performance issue relating to deferred execution of weighted mapping generation

### PR DESCRIPTION
**Pull request by mohammadshahabrafiq**
Hello Paul,

We have been using the Modulus Checker to perform validation on a large batch of sort code and account number combinations (40,000+) and we have not been getting the performance we need. I looked into the code and noticed that the code in the constructor for the ValacdosSource class is code which builds up the weight mappings based upon the Valacdos embedded file.

On every call to CheckBankAccount this mapping code is being executed. The Linq query is being deferred until the call to CheckBankAccount and is happening on every call. I have modified the code so we execute the query in the constructor by doing a ToArray and this solves our problem. We are then building mappings based on a in memory array.

I have also made some RegEx performance improvements for your inspection.

P.S I have knocked up a little program and some random test data for you to play with. See below. Not sure how to get the test data to you.

Best of regards

Mohammad

```
using ModulusChecking;
using System;
using System.Diagnostics;
using System.IO;
using System.Linq;

namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            var index = 0;
            var modulusChecker = new ModulusChecker();
            var stopwatch = new Stopwatch();

            using (var sr = new StreamReader("sa.txt"))
            {
                stopwatch.Start();

                while (sr.Peek() >= 0)
                {
                    var segments = sr
                        .ReadLine()
                        .Split('\t');

                    Console.WriteLine($"index - {index++} result - {modulusChecker.CheckBankAccount(segments.First(), segments.Last())}");
                }

                stopwatch.Stop();
            }

            Console.WriteLine($"Done in {stopwatch.Elapsed.Hours:00}:{stopwatch.Elapsed.Minutes:00}:{stopwatch.Elapsed.Seconds:00}.{stopwatch.Elapsed.Milliseconds / 10:00}");
            Console.ReadLine();
        }
    }
}
```

### CODE REVIEW

**Comment by pauldambra** [comment]
How large is the test data? Would be happy to have it as a test that asserts we can process n records in m seconds if that's helpful to you...

What performance improvement did you see?

Thanks for the contribution!

**Comment by mohammadshahabrafiq** [comment]
[sa.txt](https://github.com/pauldambra/ModulusChecker/files/687544/sa.txt)

This is the file that I am using (randomly generated) with the code that I have given and I am processing the file in about 11 minutes. With the code fix I get it within 20 seconds. This is sufficient for our needs.

I was thinking about converting that program code to a test but I felt it might not be appropriate as a unit test. I can do that if you wish.

**Comment by pauldambra** [comment]
That's an awesome improvement. I was only ever using it for small numbers at a time so never had to care.

I really like adding tests at this level - particularly when they describe a real performance/functional requirement. So here we're saying that we have a new requirement that we should be able to process 40000 records in 20 seconds or less (depending on appveyors hardware :))

Helps avoid regression in future as well!

**Comment by mohammadshahabrafiq** [comment]
Sure thing. Leave it with me I`ll get it in.

**Comment by mohammadshahabrafiq** [comment]
I have now added a performance unit test. Its now processing the file in under a second. 😄

**Comment by pauldambra** [comment]
That's so awesome that you contributed your changes back @dezzy30000.

You've made my week :)

Published as 1.4.1 on nuget now. Thanks again!

**Comment by mohammadshahabrafiq** [comment]
No problem. Glad I could contribute. Need to do it more.

**Pull request merged**
