### PR TITLE
Update valacdos to v500

### PR DESCRIPTION
**Pull request by rokeyge**
https://www.vocalink.com/media/3019/vocalink-validating-account-numbers-v500.pdf

Updating the valacdos file that will go live on Aug 6th 2018.

https://www.vocalink.com/media/3020/valacdos.txt

### CODE REVIEW

**Comment by pauldambra** [comment]
Brilliant, thanks!

Can we bump to 2.2.0 instead of 2.1.1? It's a change not a fix.

**Comment by rokeyge** [comment]
Sure!

**Comment by rokeyge** [comment]
Heya, any chance of getting this reviewed please? :cake:

**Review by pauldambra — APPROVED** [review]

**Comment by pauldambra** [comment]
Really appreciate the PR! 

Thank you

**Comment by rokeyge** [comment]
:+1:  You're welcome!

Have you set it up to auto upload to nuget now, or is it still a manual step?

**Comment by pauldambra** [comment]
Still a manual step. Published now https://www.nuget.org/packages/ModulusChecker/

**Pull request merged**
