### PR TITLE
Updated modulus weights to version 3.7

### PR DESCRIPTION
**Pull request by stephenbinns**
This change is simply to take the latest modulus weights from the vocalink site:
https://www.vocalink.com/media/1785/valacdos-v370.txt

The Sort code subsitutions have not been changed for v3.7

### CODE REVIEW

**Comment by pauldambra** [comment]
Awesome thanks! I don't use this library day to day anymore so hadn't seen the change to 3.7

I'll check this after work today or tomorrow (although I can't see anything in the commits that should cause a problem)

I'd forgotten that I'd started adding travis-ci integration so that failure is my bad not your change :)

**Comment by stephenbinns** [comment]
Thanks! Its a shame there doesn't seem to be a fixed place to check for updates to the weights, do you know if vocalink provide any way for checking?

**Comment by pauldambra** [comment]
No, or rather they didn't when I last worked on the project where we were
using this. I was signed up for email updates when changes were made but I
guess I was silly and used that work email address (which doesn't exist
anymore)

**Comment by pauldambra** [comment]
Out of interest what version of dot net are you using this with. There's quite a bit of jumping though hoops to support 3.5, 4, and 4.5

Am tempted to make a major version release that only has 4.5 and 4.6

And thanks again for the PR!

**Comment by stephenbinns** [comment]
We're on 4.0 at the moment due to some legacy components that said we don't have a compelling reason not to upgrade

**Pull request merged**
